import glob from 'glob';

export const fileTip =
  'This file is auto generated by @liangskyli/routing-controllers-openapi, do not edit!';

export const getFilesFromControllers = (paths: string[]): string[] => {
  const result: string[] = paths.reduce(
    (controllerPaths: string[], controllerConfigPath: string) => {
      controllerPaths = controllerPaths.concat(glob.sync(controllerConfigPath));
      return controllerPaths;
    },
    [],
  );
  return [...new Set(result)];
};
