import { colors, copyOptions, prettierData } from '@liangskyli/utils';
import fs from 'fs-extra';
import { globSync } from 'glob';
import type { IGenOpenapiDataOpts } from './gen';

export const fileTip =
  'This file is auto generated by @liangskyli/routing-controllers-openapi, do not edit!';

export const getFilesFromControllers = (paths: string[]): string[] => {
  const result: string[] = paths.reduce(
    (controllerPaths: string[], controllerConfigPath: string) => {
      controllerPaths = controllerPaths.concat(globSync(controllerConfigPath));
      return controllerPaths;
    },
    [],
  );
  return [...new Set(result)];
};

type IWriteFileOpts = {
  prettierOptions: IGenOpenapiDataOpts['prettierOptions'];
  absolutePath: string;
  data: string;
  successTip: string;
};
export const writePrettierFile = (opts: IWriteFileOpts) => {
  const { absolutePath, prettierOptions, data, successTip } = opts;

  fs.writeFileSync(
    absolutePath,
    prettierData(data, copyOptions(prettierOptions)),
  );

  console.info(colors.green(successTip));
};
